dependencies:
  keywords:
    - "dependabot"
    - "dependency"
    - "dependencies"
  labels:
    - "dependencies"
    - "security"
    - "good first issue"

security:
  keywords:
    - "security"
  labels:
    - "security"
    - "good first issue"

design:
  keywords:
    - "layout"
    - "screen"
    - "design"
    - "figma"
  labels:
    - "ui/ux"
    - "good first issue"
