##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Checking workflow files
on:
  pull_request:
    paths:
      - '.github/**'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/main.dart'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  Checking-for-unauthorized-file-changes:
# <<<<<<< HEAD
# =======
    if: ${{ github.actor != 'dependabot[bot]' }}
# >>>>>>> 67ce8e0ca5c44e11edb4cacddfbbee7708c7b02b
    name: Checking for unauthorized file changes
    runs-on: ubuntu-latest

    steps:
      - name: Unauthorized file modification in PR
        run: exit 1
