##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

# name: Issues Workflow
# on:
#   issues:
#       types: ['opened']
# jobs:
#   Opened-issue-label:
#     name: Adding Issue Label
#     runs-on: ubuntu-latest
#     steps:
#       - uses: Renato66/auto-label@v2.3.0
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           ignore-comments: true
#           default-labels: '["unapproved"]'
  
#   Issue-Greeting:
#     name: Greeting Message to User
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/first-interaction@v1
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           issue-message: "Congratulations on making your first Issue! :confetti_ball: If you haven't already, check out our [Contributing Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) and [Issue Reporting Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/develop/ISSUE_GUIDELINES.md) to ensure that you are following our guidelines for contributing and making issues."

name: Issues Workflow
on:
  issues:
    types: ['opened', 'edited']  # Trigger on both new and edited issues

jobs:
  Opened-issue-label:
    name: Adding Issue Label
    runs-on: ubuntu-latest
    steps:
      - name: Auto Label Issues Based on Content
        uses: Renato66/auto-label@v2.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true

  # Add specific labels based on keywords in the issue body
  Auto-Label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels for Dependencies, Security, and Design
        if: github.event.issue.body != ''
        run: |
          issue_body="${{ github.event.issue.body }}"

          # Check for "dependencies" related keywords and add labels
          if echo "$issue_body" | grep -qiE "dependabot|dependency|dependencies"; then
            gh issue edit ${{ github.event.issue.number }} --add-label "dependencies"
            gh issue edit ${{ github.event.issue.number }} --add-label "security"
            gh issue edit ${{ github.event.issue.number }} --add-label "good first issue"
          fi

          # Check for "security" related keywords and add labels
          if echo "$issue_body" | grep -qiE "security"; then
            gh issue edit ${{ github.event.issue.number }} --add-label "security"
            gh issue edit ${{ github.event.issue.number }} --add-label "good first issue"
          fi

          # Check for "design" related keywords and add labels
          if echo "$issue_body" | grep -qiE "layout|screen|design|figma"; then
            gh issue edit ${{ github.event.issue.number }} --add-label "ui/ux"
            gh issue edit ${{ github.event.issue.number }} --add-label "good first issue"
          fi

  # Send a greeting message to users for new issues
  Issue-Greeting:
    name: Greeting Message to User
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congratulations on making your first Issue! :confetti_ball: If you haven't already, check out our [Contributing Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) and [Issue Reporting Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/develop/ISSUE_GUIDELINES.md) to ensure that you are following our guidelines for contributing and making issues."
